### ISSUE TITLE
Create a library (for better integration with other projects)

### ISSUE THREAD

**Issue by clapautius** [ImageProcessing-ElectronicPublications/noteshrink-c#2]
I think it would be useful to create o library for this project, to separate the CLI from the main functionality.

I'm trying to integrate this into my GUI front-end - noteshrink-qt (I'm a frequent noteshrink user 😉 ) and this looks promising (and faster than the py version).

FYI: I think I could do the PRs myself. There are some CMake changes and moving some code from main.c to a separate file.

P.S. One of the reasons I'm asking this is that I needed to copy a lot of your code in order to integrate the project into my front-end. A library would be better.

**Comment by zvezdochiot** [comment]
Hi @clapautius .

See https://github.com/ImageProcessing-ElectronicPublications/noteshrink-c/blob/master/include/noteshrink.h .
I don't see anything in `main.c` that could go into this file. **Or do you want to link the project to STB?** Do something stupid in your fork, it won't happen in mine.

**Comment by clapautius** [comment]
Hi @zvezdochiot .

**Comment by clapautius** [comment]
Hi @zvezdochiot 

I was thinking about something like NSHProcessFile(input, output), but nevermind.
I'll probably link directly to the STB project - but I'll copy some portion of your main.c 😉 - a maintenance burden, but ... heh.
You can close the issue now.

**Comment by zvezdochiot** [comment]
Hi @clapautius .

Let it be. The question of the library is possible. Whether only such library is necessary?

PS: And I don't understand why you need STB if you have Qt?

**Comment by clapautius** [comment]
Sorry that was a misunderstanding.
